import React from 'react';
import { Metadata } from 'next';
import _classes from './root-layout.module.scss';
import { ClientInit } from '@/app/client-init';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type TProps = Readonly<{
  children: React.ReactNode;
}>;

export const RootLayout = ({ children }: TProps) => {
  return (
    <html lang="ru">
      <body>{children}</body>
      <ClientInit />
    </html>
  );
};
